stages:
  - build
  - test
  - deploy

job build:
     stage: build
     tags:
       - ci
     before_script:
       - docker info
     script:
       - echo "Build"
       - docker build -t brandadr/garden-journal-frontend:latest ./garden-journal-frontend
       - docker push brandadr/garden-journal-frontend:latest
       - docker build -t brandadr/garden-journal-backend:latest ./garden-journal-backend
       - docker push brandadr/garden-journal-backend:latest
       
job test:
     stage: test
     tags:
       - ci
     script:   
       - echo "Test"

job deploy:
     stage: deploy
     tags:
       - ci
     script:
       - echo "Deploy"
       - docker rm --force garden-journal-frontend || true
       - docker pull brandadr/garden-journal-frontend:latest
       - docker run -p 8101:4200 -d --name garden-journal-frontend brandadr/garden-journal-frontend:latest
       - docker rm --force garden-journal-backend || true
       - docker pull brandadr/garden-journal-backend:latest
       - docker run -p 8100:8080 -d --name garden-journal-backend brandadr/garden-journal-backend:latest