version: '3'
services:
  backend:
    #image: brandadr/garden-journal-backend:latest
    image: brandfactoryacr.azurecr.io/garden-journal-backend:latest
    ports:
      - '80:8080'
    links: [gj_db]
  gj_db:
    image: "postgres:11.4"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: gj_db
      POSTGRES_PASSWORD: root
      PGGSSENCMODE=disable