version: '2.4'
services:
  backend:
    build: garden-journal-backend
    image: garden-journal-backend
    ports:
      - '8080:8080'
  frontend:
    links: [backend]
    build: garden-journal-frontend
    image: garden-journal-frontend
    ports:
      - '80:80'